/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Notification;
import BackEnd.NotificationManager;
import BackEnd.UserManager;
import java.awt.Color;
import java.time.LocalDate;

/**
 *
 * @author ryano
 */
public class AnnouncementScreen extends javax.swing.JFrame {

    /**
     * Creates new form AnnouncementScreen
     */
    public AnnouncementScreen() {
        Notification temp;
        initComponents();
        setLocationRelativeTo(null);
        lblError.setText("");
        lblError.setForeground(Color.red);
        if (validateInfo()) {//when creating the notification, we decrypt the contents calling the method, decryoptMessage
            temp = new Notification(UserManager.getCurrentUser().getEmail(), cbxForAll.isSelected(),
                     txfTo.getText(), LocalDate.now(), NotificationManager.decryptMessage(txaBody.getText()));
            if (cbxNotification.isSelected()) {
                NotificationManager.addNotification(temp);
            }
        }
    }
    
    private boolean validateInfo(){
        if (txfSubject.getText().isEmpty() || txfTo.getText().isEmpty() || txaBody.getText().isEmpty()) {
            lblError.setForeground(Color.red);
            lblError.setText("Missing information");
            return false;
        } else if (txfSubject.getText().contains("#") || txfTo.getText().contains("#") || txaBody.getText().contains("#")) {
            lblError.setForeground(Color.red);
            lblError.setText("Error: Contents contain a \"#\"");
            return false;
        }else if (!txfTo.getText().matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
            lblError.setForeground(Color.red);
            lblError.setText("Email incorrect format");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblSubject = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        txfSubject = new javax.swing.JTextField();
        txfTo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaBody = new javax.swing.JTextArea();
        cbxForAll = new javax.swing.JCheckBox();
        cbxEmail = new javax.swing.JCheckBox();
        lblBody = new javax.swing.JLabel();
        cbxNotification = new javax.swing.JCheckBox();
        btnPublish = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSubject.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblSubject.setForeground(new java.awt.Color(47, 56, 120));
        lblSubject.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubject.setText("Subject:");
        pnlMain.add(lblSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        lblTo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblTo.setForeground(new java.awt.Color(47, 56, 120));
        lblTo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTo.setText("To:");
        pnlMain.add(lblTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 50, -1));

        txfSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSubjectActionPerformed(evt);
            }
        });
        pnlMain.add(txfSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 230, -1));

        txfTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfToActionPerformed(evt);
            }
        });
        pnlMain.add(txfTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 230, -1));

        txaBody.setColumns(20);
        txaBody.setRows(5);
        jScrollPane1.setViewportView(txaBody);

        pnlMain.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 460, 140));

        cbxForAll.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        cbxForAll.setForeground(new java.awt.Color(47, 56, 120));
        cbxForAll.setText("For all users");
        cbxForAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxForAllActionPerformed(evt);
            }
        });
        pnlMain.add(cbxForAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        cbxEmail.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        cbxEmail.setForeground(new java.awt.Color(47, 56, 120));
        cbxEmail.setText("Emailed to recipients");
        cbxEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEmailActionPerformed(evt);
            }
        });
        pnlMain.add(cbxEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        lblBody.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblBody.setForeground(new java.awt.Color(47, 56, 120));
        lblBody.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBody.setText("Body:");
        pnlMain.add(lblBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        cbxNotification.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        cbxNotification.setForeground(new java.awt.Color(47, 56, 120));
        cbxNotification.setText("Notify Recipients");
        cbxNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNotificationActionPerformed(evt);
            }
        });
        pnlMain.add(cbxNotification, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        btnPublish.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        btnPublish.setForeground(new java.awt.Color(47, 56, 120));
        btnPublish.setText("Publish");
        btnPublish.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 57, 120)));
        btnPublish.setContentAreaFilled(false);
        btnPublish.setFocusPainted(false);
        pnlMain.add(btnPublish, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 80, -1));

        lblError.setForeground(new java.awt.Color(153, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("lblError");
        pnlMain.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 230, -1));

        lblBackground.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lblBackground.setForeground(new java.awt.Color(47, 56, 120));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginBackground.png"))); // NOI18N
        lblBackground.setText("jLabel1");
        pnlMain.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 764, 430));

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSubjectActionPerformed

    private void txfToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfToActionPerformed

    private void cbxForAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxForAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxForAllActionPerformed

    private void cbxEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEmailActionPerformed

    private void cbxNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNotificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNotificationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnnouncementScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnnouncementScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnnouncementScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnnouncementScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnnouncementScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPublish;
    private javax.swing.JCheckBox cbxEmail;
    private javax.swing.JCheckBox cbxForAll;
    private javax.swing.JCheckBox cbxNotification;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBody;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTo;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextArea txaBody;
    private javax.swing.JTextField txfSubject;
    private javax.swing.JTextField txfTo;
    // End of variables declaration//GEN-END:variables
}
