/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Student;
import BackEnd.Teacher;
import BackEnd.TimetableManager;
import BackEnd.UserManager;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.NoSuchElementException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ryano
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        lblError.setText("");
        setLocationRelativeTo(null);
        
    }
    public void autoLogin(){
        if (checkPrevInfo()) {
            lblError.setForeground(Color.GREEN);
            lblError.setText("Valid");
            
            UserManager.setCurrentUser(user);
            TimetableManager.setCurrentUser(user);
            TimetableManager.setSchoolCode(schoolcode);
            UserManager.loadInfo(schoolcode);
            
            MainMenuScreen mm = new MainMenuScreen();
            mm.setVisible(true);
            this.dispose();
        }
    }
    private boolean checkPrevInfo(){
        try{
            Scanner scFile = new Scanner(new File("PrevLogin.txt")).useDelimiter("#");
            String line1 = scFile.nextLine();
            String line2 = scFile.nextLine();
            
            String[] first = line1.split("#");
            
            LocalDate prevLoginDate = LocalDate.parse(first[0], DateTimeFormatter.ofPattern("dd-MM-yyyy"));
            schoolcode = first[1];
            
            int prevLogin = Period.between(prevLoginDate, LocalDate.now()).getDays();
            if (prevLogin < 30) {
                String[] second = line2.split("#");
                String name = second[0];
                String surname = second[1];
                String email = second[2];
                String password = second[3];
                String DOB = second[4];
                boolean isAdmin = Boolean.parseBoolean(second[5]);
                if (!isAdmin) {
                    int grade = Integer.parseInt(second[6]);
                    user = new Student(name, surname, email, password, DOB, grade, isAdmin);
                }
                else if(isAdmin){
                    String subject = second[7];
                    user = new Teacher(name, surname, email, password, DOB, -1, isAdmin, subject); 
                }
                return true;
            }
            scFile.close();
        }   catch (FileNotFoundException f){
            System.out.println("Couldn't Find Prev Login File\n"+f);
        }   catch (NoSuchElementException f){
            return false;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblSchoolCode = new javax.swing.JLabel();
        txfEmail = new javax.swing.JTextField();
        txfSchoolCode = new javax.swing.JTextField();
        psfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JToggleButton();
        btnCreateSchool = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(47, 56, 120));
        lblTitle.setText("StudTab");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        lblEmail.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(47, 56, 120));
        lblEmail.setText("Email");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 40, -1));

        lblPassword.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(47, 56, 120));
        lblPassword.setText("Password");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, -1));

        lblSchoolCode.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblSchoolCode.setForeground(new java.awt.Color(47, 56, 120));
        lblSchoolCode.setText("School Code");
        jPanel1.add(lblSchoolCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 80, -1));

        txfEmail.setBackground(new java.awt.Color(240, 240, 240));
        txfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 230, -1));

        txfSchoolCode.setBackground(new java.awt.Color(240, 240, 240));
        txfSchoolCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSchoolCodeActionPerformed(evt);
            }
        });
        jPanel1.add(txfSchoolCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 90, -1));

        psfPassword.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.add(psfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 170, -1));

        btnLogin.setBackground(new java.awt.Color(240, 240, 240));
        btnLogin.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(47, 56, 120));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 56, 120)));
        btnLogin.setContentAreaFilled(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 120, -1));

        btnCreateSchool.setBackground(new java.awt.Color(240, 240, 240));
        btnCreateSchool.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        btnCreateSchool.setForeground(new java.awt.Color(47, 56, 120));
        btnCreateSchool.setText("CreateSchool");
        btnCreateSchool.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCreateSchool.setContentAreaFilled(false);
        btnCreateSchool.setFocusPainted(false);
        jPanel1.add(btnCreateSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 120, -1));

        lblError.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(204, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("jLabel3");
        jPanel1.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 370, 20));

        lblBackGround.setBackground(new java.awt.Color(240, 240, 240));
        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginBackground.png"))); // NOI18N
        jPanel1.add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEmailActionPerformed

    private void txfSchoolCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSchoolCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSchoolCodeActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        String schoolCode = txfSchoolCode.getText();
        if (UserManager.loadInfo(schoolCode)) {
            String email = txfEmail.getText();
            String password = String.valueOf(psfPassword.getPassword());
            
            Student User = UserManager.checkInfo(email, password, schoolCode);
            if (User == null) {
                ///
                lblError.setText("Incorrect Email or Password");
            }else{
                lblError.setForeground(Color.GREEN);
                lblError.setText("Valid");
                UserManager.setCurrentUser(User);
                TimetableManager.setCurrentUser(User);
                TimetableManager.setSchoolCode(schoolCode);
                
                try {
                    FileWriter prevLogin = new FileWriter("PrevLogin.txt");
                    String temp;
                    temp = LocalDate.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy"))+"#"+schoolCode+"\n"+User.printStudent();
                    prevLogin.write(temp);
                    prevLogin.close();
                    
                } catch (IOException ex) {
                    Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                MainMenuScreen mm = new MainMenuScreen();
                mm.setVisible(true);
                this.dispose();
            }
        }else{
            lblError.setText("Couldn't Locate User File");
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    public String getSchoolCode(){
        return txfSchoolCode.getText();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginScreen ls = new LoginScreen();
                ls.setVisible(true);
                ls.autoLogin();//fixing error where loginscreen wouldnt close
            }
        });
    }

    private Student user;
    private String schoolcode;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateSchool;
    private javax.swing.JToggleButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSchoolCode;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPasswordField psfPassword;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfSchoolCode;
    // End of variables declaration//GEN-END:variables
}
