/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.NotificationManager;
import BackEnd.Teacher;
import BackEnd.TimetableManager;
import BackEnd.UserManager;
import java.awt.Image;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author ryano
 */
public class MainMenuScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuScreen
     */
    public MainMenuScreen() {
        initComponents();
        setLocationRelativeTo(null);
        NotificationManager.loadInfo();
        lstNotifications.setVisible(false);
        jScrollPane1.setVisible(false);//note for self, how to propperly hide element.
        setupNotifications();
        
        lblDOB.setText(UserManager.getCurrentUser().getDOB());
        lblStudentName.setText(UserManager.getCurrentUser().getName()+" "+UserManager.getCurrentUser().getSurname());
        if (UserManager.getCurrentUser() instanceof Teacher) {
            lblGradeIcon.setText("Subject");
            lblGrade.setText(String.valueOf(UserManager.getCurrentUser().getSubject()));
        }else{
            lblGradeIcon.setText("Subject");
            lblGrade.setText(String.valueOf(UserManager.getCurrentUser().getGrade()));
        }
        
        String path = "data/"+TimetableManager.getSchoolCode()+"/Pictures/" + UserManager.getCurrentUser().getName()+UserManager.getCurrentUser().getSurname() + ".jpg";
        
        File imgFile = new File(path);
        if (imgFile.exists()) {
            ImageIcon icon = new ImageIcon(path);
            Image scaled = icon.getImage().getScaledInstance(
                lblProfilePic.getWidth(), 
                lblProfilePic.getHeight(), 
                Image.SCALE_SMOOTH
            );
            lblProfilePic.setIcon(new ImageIcon(scaled));
            lblProfilePic.revalidate();
            lblProfilePic.repaint();
            System.out.println("Icon Set");
        } else {
            System.out.println("Couldn't locate profile picture: " + path +"\nIcon Set To Defualt.");
            
        }
        
        btnViewTimetable.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));//rounded edges
        if (!UserManager.getCurrentUser().getIsAdmin()) {
            btnAddStudent.setEnabled(false);
            btnAddStudent.setVisible(false);
        }
    }
    
    /**
     * by making this a void method i have more functionality and can easily terminate 
     * the method and do checking in other methods
     * @return 
     */
    private DefaultListModel<String>notificationsModel;
    private boolean setupNotifications(){
        notificationsModel = new DefaultListModel<>();
        lstNotifications.setModel(notificationsModel);// replaces NetBeans' fixed placeholder model
        String temp = "Notification added:\t";
        int numNotif = NotificationManager.getNumNotificationsForUser(UserManager.getCurrentUser());
        String[] notif = new String[numNotif];
        notif = NotificationManager.getNotificationsForUser(UserManager.getCurrentUser());
        for (int i = 0; i < numNotif; i++) {
            notificationsModel.addElement(notif[i]);
            temp+= notif[i] + "\t";
        }
        System.out.println(temp);
        return true;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewTimetable = new javax.swing.JButton();
        pnlMainMenu = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlDetails = new javax.swing.JPanel();
        lblStudentName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblGradeIcon = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGrade = new javax.swing.JLabel();
        lblProfilePic = new javax.swing.JLabel();
        btnAddStudent = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnNotifications = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNotifications = new javax.swing.JList<>();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewTimetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnViewTimetable.png"))); // NOI18N
        btnViewTimetable.setBorderPainted(false);
        btnViewTimetable.setContentAreaFilled(false);
        btnViewTimetable.setFocusPainted(false);
        btnViewTimetable.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnRollViewTimetable.png"))); // NOI18N
        btnViewTimetable.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnViewTimetable.png"))); // NOI18N
        btnViewTimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTimetableActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewTimetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 177, 50));

        pnlMainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(47, 56, 120));
        lblTitle.setText("StudTab");
        pnlMainMenu.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 120, 40));

        pnlDetails.setBackground(new java.awt.Color(250, 250, 250));
        pnlDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 57, 120), 2));
        pnlDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStudentName.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(47, 56, 120));
        lblStudentName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentName.setText("name");
        pnlDetails.add(lblStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 56, 120));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("DOB:");
        pnlDetails.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, -1));

        lblGradeIcon.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lblGradeIcon.setForeground(new java.awt.Color(47, 56, 120));
        lblGradeIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGradeIcon.setText("Grade:");
        pnlDetails.add(lblGradeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 40, -1));

        lblDOB.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(47, 56, 120));
        lblDOB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDOB.setText("date of birth");
        pnlDetails.add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 100, -1));

        lblGrade.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lblGrade.setForeground(new java.awt.Color(47, 56, 120));
        lblGrade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGrade.setText("grade / subject");
        pnlDetails.add(lblGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 90, -1));

        lblProfilePic.setText("Icon");
        pnlDetails.add(lblProfilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 120));

        pnlMainMenu.add(pnlDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 190, 210));

        btnAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnViewStudents.png"))); // NOI18N
        btnAddStudent.setBorderPainted(false);
        btnAddStudent.setContentAreaFilled(false);
        btnAddStudent.setFocusPainted(false);
        btnAddStudent.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnRollViewStudents.png"))); // NOI18N
        btnAddStudent.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnViewStudents.png"))); // NOI18N
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });
        pnlMainMenu.add(btnAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 177, 50));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnLogout.png"))); // NOI18N
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnRollLogout.png"))); // NOI18N
        btnLogout.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnLogout.png"))); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlMainMenu.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 50, 50));

        btnNotifications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnNotifications.png"))); // NOI18N
        btnNotifications.setBorderPainted(false);
        btnNotifications.setContentAreaFilled(false);
        btnNotifications.setFocusPainted(false);
        btnNotifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificationsActionPerformed(evt);
            }
        });
        pnlMainMenu.add(btnNotifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 30, 30));

        lstNotifications.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(47, 56, 120), 2, true));
        lstNotifications.setForeground(new java.awt.Color(47, 56, 120));
        lstNotifications.setToolTipText("");
        jScrollPane1.setViewportView(lstNotifications);

        pnlMainMenu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 200, 80));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginBackground.png"))); // NOI18N
        pnlMainMenu.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        getContentPane().add(pnlMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewTimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTimetableActionPerformed
        TimetableScreen tt = new TimetableScreen(this);
        tt.setVisible(true);
        this.setVisible(false);//hiding screen not disposing
    }//GEN-LAST:event_btnViewTimetableActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            FileWriter prevFile = new FileWriter("PrevLogin.txt");
            prevFile.write("");
            prevFile.close();
        } catch (IOException ex) {
            System.out.println("IO Exception\n"+ex);
        }
        LoginScreen ls = new LoginScreen();
        ls.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        ManageStudentsScreen ms  = new ManageStudentsScreen(this);
        ms.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnNotificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificationsActionPerformed
        if (lstNotifications.isVisible()) {
            lstNotifications.setVisible(false);
            jScrollPane1.setVisible(false);
        }else{
            lstNotifications.setVisible(true);
            jScrollPane1.setVisible(true);
        }
        
    }//GEN-LAST:event_btnNotificationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNotifications;
    private javax.swing.JButton btnViewTimetable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblGradeIcon;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstNotifications;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlMainMenu;
    // End of variables declaration//GEN-END:variables
}
