/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.UserManager;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ryano
 */
public class MainMenuScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuScreen
     */
    public MainMenuScreen() {
        initComponents();
        setLocationRelativeTo(null);
        lblStudentName.setText(UserManager.getCurrentUser().getName()+" "+UserManager.getCurrentUser().getSurname());
        lblDOB.setText(UserManager.getCurrentUser().getDOB());
        lblGrade.setText(String.valueOf(UserManager.getCurrentUser().getGrade()));
        String path = "src/Images/" + UserManager.getCurrentUser().getEmail() + ".jpg";
        ImageIcon icon = new ImageIcon(path);
        lblProfilePic.setIcon(icon);
        btnViewTimetable.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));//rounded edges
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewTimetable = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlDetails = new javax.swing.JPanel();
        lblStudentName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGrade = new javax.swing.JLabel();
        lblProfilePic = new javax.swing.JLabel();
        btnAddStudent = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewTimetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnViewTimetable.png"))); // NOI18N
        btnViewTimetable.setBorderPainted(false);
        btnViewTimetable.setContentAreaFilled(false);
        btnViewTimetable.setFocusPainted(false);
        btnViewTimetable.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnRollViewTimetable.png"))); // NOI18N
        btnViewTimetable.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnViewTimetable.png"))); // NOI18N
        btnViewTimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTimetableActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewTimetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 177, 50));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 80, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(47, 56, 120));
        lblTitle.setText("StudTab");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 120, 40));

        pnlDetails.setBackground(new java.awt.Color(250, 250, 250));
        pnlDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 57, 120), 2));
        pnlDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStudentName.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(47, 56, 120));
        lblStudentName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentName.setText("jLabel1");
        pnlDetails.add(lblStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 56, 120));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("DOB:");
        pnlDetails.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(47, 56, 120));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Grade:");
        pnlDetails.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 40, -1));

        lblDOB.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(47, 56, 120));
        lblDOB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDOB.setText("jLabel3");
        pnlDetails.add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 100, -1));

        lblGrade.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        lblGrade.setForeground(new java.awt.Color(47, 56, 120));
        lblGrade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGrade.setText("jLabel4");
        pnlDetails.add(lblGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 90, -1));

        lblProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/26344@stjohnscollege.co.za.jpg"))); // NOI18N
        lblProfilePic.setText("jLabel3");
        pnlDetails.add(lblProfilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 120));

        jPanel1.add(pnlDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 190, 210));

        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginBackground.png"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewTimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTimetableActionPerformed
        TimetableScreen tt = new TimetableScreen(this);
        tt.setVisible(true);
        this.setVisible(false);//hiding screen not disposing
    }//GEN-LAST:event_btnViewTimetableActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            FileWriter prevFile = new FileWriter("PrevLogin.txt");
            prevFile.write("");
            prevFile.close();
        } catch (IOException ex) {
            System.out.println("IO Exception\n"+ex);
        }
        LoginScreen ls = new LoginScreen();
        ls.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        AddUserScreen as = new AddUserScreen(this);
        as.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewTimetable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlDetails;
    // End of variables declaration//GEN-END:variables
}
